/* tslint:disable */
/* eslint-disable */
/**
 * EDIS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Team
 */
export interface Team {
    /**
     * 
     * @type {number}
     * @memberof Team
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof Team
     */
    'totalscore': number;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    'teamcategory': string;
    /**
     * 
     * @type {Array<number>}
     * @memberof Team
     */
    'scores': Array<number>;
}

